# Generated by Django 3.0.2 on 2020-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liczby_tekst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=255)),
                ('textOutput', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
